---
"nominal":
  - 'MS SubClass'
  - 'MS Zoning'
  - 'Street'
  - 'Alley'
  - 'Land Contour'
  - 'Lot Config'
  - 'Neighborhood'
  - 'Condition 1'
  - 'Condition 2'
  - 'Bldg Type'
  - 'House Style'
  - 'Roof Style'
  - 'Roof Matl'
  - 'Exterior 1st'
  - 'Exterior 2nd'
  - 'Mas Vnr Type'
  - 'Foundation'
  - 'Heating'
  - 'Central Air'
  - 'Garage Type'
  - 'Misc Feature'
  - 'Sale Type'
  - 'Sale Condition'

"ordinal":
  - 'Lot Shape'
  - 'Utilities'
  - 'Land Slope'
  - 'Exter Qual'
  - 'Exter Cond'
  - 'Bsmt Qual'
  - 'Bsmt Cond'
  - 'Bsmt Exposure'
  - 'BsmtFin Type 1'
  - 'BsmtFin Type 2'
  - 'Heating QC'
  - 'Electrical'
  - 'Kitchen Qual'
  - 'Functional'
  - 'Fireplace Qu'
  - 'Garage Finish'
  - 'Garage Qual'
  - 'Garage Cond'
  - 'Paved Drive'
  - 'Pool QC'
  - 'Fence'

"discrete":
  - 'Overall Qual'
  - 'Overall Cond'
  - 'Year Built'
  - 'Year Remod/Add'
  - 'Bsmt Full Bath'
  - 'Bsmt Half Bath'
  - 'Full Bath'
  - 'Half Bath'
  - 'Bedroom AbvGr'
  - 'Kitchen AbvGr'
  - 'TotRms AbvGrd'
  - 'Fireplaces'
  - 'Garage Yr Blt'
  - 'Garage Cars'
  - 'Mo Sold'
  - 'Yr Sold'

"continuous":
  - 'Lot Frontage'
  - 'Lot Area'
  - 'Mas Vnr Area'
  - 'BsmtFin SF 1'
  - 'BsmtFin SF 2'
  - 'Bsmt Unf SF'
  - 'Total Bsmt SF'
  - '1st Flr SF'
  - '2nd Flr SF'
  - 'Low Qual Fin SF'
  - 'Gr Liv Area'
  - 'Garage Area'
  - 'Wood Deck SF'
  - 'Open Porch SF'
  - 'Enclosed Porch'
  - '3Ssn Porch'
  - 'Screen Porch'
  - 'Pool Area'
  - 'Misc Val'
