"MS SubClass": 'Dwelling Type'
"MS Zoning": 'Zoning Classification'
"Lot Frontage": 'Lot Frontage (sf)'
"Lot Area": 'Lot Area (sf)'
"Street": 'Street Type'
"Alley": 'Alley Type'
"Lot Shape": 'Lot Shape'
"Land Contour": 'Property Flatness'
"Utilities": 'Available Utilities'
"Lot Config": 'Lot Configuration'
"Land Slope": 'Land Slope'
"Neighborhood": 'Neighborhood'
"Condition 1": 'Condition Near'
"Condition 2": 'Condition Near'
"Bldg Type": 'Building Type'
"House Style": 'House Style'
"Overall Qual": 'Overall Quality'
"Overall Cond": 'Overall Condition'
"Year Built": 'Year Built'
"Year Remod/Add": 'Remodelling Year'
"Roof Style": 'Roof Style'
"Roof Matl": 'Roof Material'
"Exterior 1st": 'Exterior Covering 1'
"Exterior 2nd": 'Exterior Covering 2'
"Mas Vnr Type": 'Masonry Veneer Type'
"Mas Vnr Area": 'Masonry Veneer Area (sf)'
"Exter Qual": 'Exterior Quality'
"Exter Cond": 'Exterior Condition'
"Foundation": 'Foundation'
"Bsmt Qual": 'Basement Quality'
"Bsmt Cond": 'Basement Condition'
"Bsmt Exposure": 'Garden Level Walls'
"BsmtFin Type 1": 'Basement 1 Rating'
"BsmtFin SF 1": 'Basement 1 Area (sf)'
"BsmtFin Type 2": 'Basement 2 Rating'
"BsmtFin SF 2": 'Basement 2 Area (sf)'
"Bsmt Unf SF": 'Unf. Basement Area (sf)'
"Total Bsmt SF": 'Total Basement Area (sf)'
"Heating": 'Heating Type'
"Heating QC": 'Heating Quality/Condition'
"Central Air": 'Central Air Conditioning'
"Electrical": 'Electrical System'
"1st Flr SF": '1st Floor Area (sf)'
"2nd Flr SF": '2nd Floor Area (sf)'
"Low Qual Fin SF": 'Low Quality Finished Area (sf)'
"Gr Liv Area": 'Abv Grade Living Area (sf)'
"Bsmt Full Bath": 'Basement Full Bathrms'
"Bsmt Half Bath": 'Basement Half Bathrms'
"Full Bath": 'Full Bathrms Abv Grade'
"Half Bath": 'Half Bathrms Abv Grade'
"Bedroom AbvGr": 'Bedrooms Abv Grade'
"Kitchen AbvGr": 'Kitchens Abv Grade'
"Kitchen Qual": 'Kitchen Quality'
"TotRms AbvGrd": 'Total Rooms Abv Grade'
"Functional": 'Home Functionality'
"Fireplaces": 'Number of Fireplaces'
"Fireplace Qu": 'Fireplace Quality'
"Garage Type": 'Garage Location'
"Garage Yr Blt": 'Garage Year Built'
"Garage Finish": 'Garage Interior Finish'
"Garage Cars": 'Garage Size (Car Capacity)'
"Garage Area": 'Garage Size (sf)'
"Garage Qual": 'Garage Quality'
"Garage Cond": 'Garage Condition'
"Paved Drive": 'Paved Driveway'
"Wood Deck SF": 'Wood Deck Area (sf)'
"Open Porch SF": 'Open Porch Area (sf)'
"Enclosed Porch": 'Enclosed Porch Area (sf)'
"3Ssn Porch": 'Three Season Porch Area (sf)'
"Screen Porch": 'Screen Porch Area (sf)'
"Pool Area": 'Pool Area (sf)'
"Pool QC": 'Pool Quality'
"Fence": 'Fence Quality'
"Misc Feature": 'Miscellaneous Feature'
"Misc Val": 'Value of Miscellaneous Feature ($)'
"Mo Sold": 'Month Sold'
"Yr Sold": 'Year Sold'
"Sale Type": 'Sale Type'
"Sale Condition": 'Sale Condition'
"SalePrice": 'Sale Price ($)'
"Ex": 'Excellent'
"Gd": 'Good'
"Av": 'Average'
"TA": 'Typical/Average'
"Mn": 'Minimum'
"Fa": 'Fair'
"Po": 'Poor'
"No": 'None'
"Grvl": 'Gravel'
"Pave": 'Paved'
"GLQ": 'Good Living Quarters'
"ALQ": 'Average Living Quarters'
"BLQ": 'Below Average Living Quarters'
"Rec": 'Average Rec Room'
"LwQ": 'Low Quality'
"Fin": 'Finished'
"RFn": 'Rough Finished'
"Unf": 'Unfinished'
"Reg": 'Regular'
"IR1": 'Slightly Irregular'
"IR2": 'Moderately Irregular'
"IR3": 'Irregular'
"AllPub": 'All public Utilities'
"NoSewr": 'Electricity, Gas, and Water (Septic Tank)'
"NoSeWa": 'Electricity and Gas Only'
"ELO": 'Electricity only'
"1Fam": 'Single-family Detached'
"2fmCon": 'Two-family Conversion'
"Duplex": 'Duplex'
"TwnhsE": 'Townhouse End Unit'
"Twnhs": 'Townhouse Inside Unit'
"N": 'No'
"P": 'Partial'
"Y": 'Yes'
"Artery": 'Adjacent to arterial street'
"Feedr": 'Adjacent to feeder street'
"Norm": 'Normal'
"RRNn": 'Within 200" of North-South Railroad'
"RRAn": 'Adjacent to North-South Railroad'
"PosN": 'Near positive off-site feature--park, greenbelt, etc.'
"PosA": 'Adjacent to postive off-site feature'
"RRNe": 'Within 200" of East-West Railroad'
"RRAe": 'Adjacent to East-West Railroad'
"Mix": 'Mixed'
"FuseP": '60 AMP Fuse Box and mostly knob & tube wiring (poor)'
"FuseF": '60 AMP Fuse Box and mostly Romex wiring (Fair)'
"FuseA": 'Fuse Box over 60 AMP and all Romex wiring (Average)'
"SBrkr": 'Standard Circuit Breakers & Romex'
"AsbShng": 'Asbestos Shingles'
"AsphShn": 'Asphalt Shingles'
"BrkComm": 'Brick Common'
"BrkCmn": 'Brick Common'
"Brk Cmn": 'Brick Common'
"BrkFace": 'Brick Face'
"BrkTil": 'Brick & Tile'
"CBlock": 'Cinder Block'
"CemntBd": 'Cement Board'
"CmentBd": 'Cement Board'
"HdBoard": 'Hard Board'
"ImStucc": 'Imitation Stucco'
"MetalSd": 'Metal Siding'
"Other": 'Other'
"PConc": 'Poured Contrete'
"Plywood": 'Plywood'
"PreCast": 'PreCast'
"Slab": 'Slab'
"Stone": 'Stone'
"Stucco": 'Stucco'
"VinylSd": 'Vinyl Siding'
"Wd Sdng": 'Wood Siding'
"WdShing": 'Wood Shingles'
"Wd Shng": 'Wood Shingles'
"Wood": 'Wood'
"MnWw": 'Minimum Wood/Wire'
"GdWo": 'Good Wood'
"MnPrv": 'Minimum Privacy'
"GdPrv": 'Good Privacy'
"Sal": 'Salvage only'
"Sev": 'Severely Damaged'
"Maj2": 'Major Deductions 2'
"Maj1": 'Major Deductions 1'
"Mod": 'Moderate Deductions'
"Min2": 'Minor Deductions 2'
"Min1": 'Minor Deductions 1'
"Typ": 'Typical Functionality'
"2Types": 'More than one type of garage'
"Attchd": 'Attached to home'
"Basment": 'Basement Garage'
"BuiltIn": 'Built-In'
"CarPort": 'Car Port'
"Detchd": 'Detached from home'
"1Story": 'One story'
"1.5Fin": 'One and one-half story: 2nd level finished'
"1.5Unf": 'One and one-half story: 2nd level unfinished'
"2Story": 'Two story'
"2.5Fin": 'Two and one-half story: 2nd level finished'
"2.5Unf": 'Two and one-half story: 2nd level unfinished'
"SFoyer": 'Split Foyer'
"SLvl": 'Split Level'
"Lvl": 'Near Flat/Level'
"Bnk": 'Banked'
"HLS": 'Hillside'
"Low": 'Depression'
"Inside": 'Inside lot'
"Corner": 'Corner lot'
"CulDSac": 'Cul-de-sac'
"FR2": 'Frontage on 2 sides of property'
"FR3": 'Frontage on 3 sides of property'
"020": '1-STORY 1946 & NEWER ALL STYLES'
"030": '1-STORY 1945 & OLDER'
"040": '1-STORY W/FINISHED ATTIC ALL AGES'
"045": '1-1/2 STORY - UNFINISHED ALL AGES'
"050": '1-1/2 STORY FINISHED ALL AGES'
"060": '2-STORY 1946 & NEWER'
"070": '2-STORY 1945 & OLDER'
"075": '2-1/2 STORY ALL AGES'
"080": 'SPLIT OR MULTI-LEVEL'
"085": 'SPLIT FOYER'
"090": 'DUPLEX - ALL STYLES AND AGES'
"120": '1-STORY PUD (Planned Unit Development) - 1946 & NEWER'
"150": '1-1/2 STORY PUD - ALL AGES'
"160": '2-STORY PUD - 1946 & NEWER'
"180": 'PUD - MULTILEVEL - INCL SPLIT LEV/FOYER'
"190": '2 FAMILY CONVERSION - ALL STYLES AND AGES'
"A (agr)": 'Agriculture'
"C (all)": 'Commercial'
"FV": 'Floating Village Residential'
"I (all)": 'Industrial'
"RH": 'Residential High Density'
"RL": 'Residential Low Density'
"RM": 'Residential Medium Density'
"Elev": 'Elevator'
"Gar2": '2nd Garage (if not described in garage section)'
"Othr": 'Other'
"Shed": 'Shed'
"TenC": 'Tennis Court'
"Blmngtn": 'Bloomington Heights'
"Blueste": 'Bluestem'
"BrDale": 'Briardale'
"BrkSide": 'Brookside'
"ClearCr": 'Clear Creek'
"CollgCr": 'College Creek'
"Crawfor": 'Crawford'
"Edwards": 'Edwards'
"Gilbert": 'Gilbert'
"Greens": 'Greens'
"GrnHill": 'Green Hills'
"IDOTRR": 'Iowa DOT and Rail Road'
"Landmrk": 'Landmark'
"MeadowV": 'Meadow Village'
"Mitchel": 'Mitchell'
"NAmes": 'North Ames'
"NPkVill": 'Northridge'
"NWAmes": 'Northpark Villa'
"NoRidge": 'Northridge Heights'
"NridgHt": 'Northwest Ames'
"OldTown": 'Old Town'
"SWISU": 'South & West of Iowa State University'
"Sawyer": 'Sawyer'
"SawyerW": 'Sawyer West'
"Somerst": 'Somerset'
"StoneBr": 'Stone Brook'
"Timber": 'Timberland'
"Veenker": 'Veenker'
"Flat": 'Flat'
"Gable": 'Gable'
"Gambrel": 'Gabrel (Barn)'
"Hip": 'Hip'
"Mansard": 'Mansard'
"Normal": 'Normal Sale'
"Abnorml": 'Abnormal Sale - trade, foreclosure, short sale'
"AdjLand": 'Adjoining Land Purchase'
"Alloca": 'Allocation - two linked properties with separate deeds'
"Family": 'Sale between family members'
"Partial": 'Home was not completed when last assessed'
"WD": 'Warranty Deed - Conventional'
"CWD": 'Warranty Deed - Cash'
"VWD": 'Warranty Deed - VA Loan'
"New": 'Home just constructed and sold'
"COD": 'Court Officer Deed/Estate'
"Con": 'Contract 15% Down payment regular terms'
"ConLw": 'Contract Low Down payment and low interest'
"ConLI": 'Contract Low Interest'
"ConLD": 'Contract Low Down'
"Oth": 'Other'
"01": 'January'
"02": 'February'
"03": 'March'
"04": 'April'
"05": 'May'
"06": 'June'
"07": 'July'
"08": 'August'
"09": 'September'
"10": 'October'
"11": 'November'
"12": 'December'
