---
- 'Low Qual Fin SF'
- '3Ssn Porch'
- 'Pool Area'
- 'Misc Val'
- 'Bsmt Half Bath'
- 'Kitchen AbvGr'
- 'Street'
- 'Condition 2'
- 'Roof Matl'
- 'Heating'
- 'Utilities'
- 'Land Slope'
- 'Garage Cond'
- 'Garage Area'
- 'TotRms AbvGrd'
- 'Fireplace Qu'
